BASE_CHECKPOINT = 'facebook/bart-base'
MODEL = 'models/bartqa/main'
MODEL_PRETRAIN = 'models/bartqa/pretrain'
TOKENIZER = 'models/bartqa/tokenizer'
DATASET_QA = 'data/bartqa/dataset_qa'
DATASET_PRETRAIN = 'data/bartqa/dataset_pretrain'
RESULTS = 'results/bartqa/main'
RESULTS_PRETRAIN = 'results/bartqa/pretrain'
